version: '3'

silent: true
 
tasks:
  default:
    cmds:
      - task: deploy:curie

  deploy:* :
    desc: Deploy to a specific target
    vars:
      TARGET: '{{index .MATCH 0}}'
      HOSTNAME:
        sh: "hostname"
      ALLOWED_TARGETS: # Dynamically get allowed targets to use in precondition
        sh: "nix flake show --json 2>/dev/null | jq -r '.nixosConfigurations | keys[]'"
      NIX_REBUILD_CMD: nixos-rebuild switch --flake .#{{.TARGET}} --no-reexec
    preconditions:
      - sh: echo '{{.ALLOWED_TARGETS}}' | grep -q '^{{.TARGET}}$'
        msg: "Target [{{.TARGET}}] is not in the list of allowed targets: [{{.ALLOWED_TARGETS}}]"
    cmds:
      - echo "    🚀 Deploying to {{.TARGET}}..."
      - cmd: sudo {{.NIX_REBUILD_CMD}}
        if: '{{eq .TARGET .HOSTNAME}}'
      - cmd: '{{.NIX_REBUILD_CMD}} --target-host "{{.TARGET}}" --build-host "{{.TARGET}}" --sudo'
        if: '{{ne .TARGET .HOSTNAME}}'
      - cmd: echo "🎉 Deployment to {{.TARGET}} completed successfully! 🎉"
  
  deploy:all:
    desc: Deploy to all targets
    deps:
      - for: [curie, ada]
        task: deploy:{{.ITEM}}

  update:
    desc: Full system update
    prompt: This will update *everything* in your systems. Do you want to continue?
    cmds:
      - nix flake update

  clean:
    desc: Remove older generations and unused packages
    cmds:
      # Delete all generations older than 7 days
      - sudo nix profile wipe-history --older-than 7d --profile /nix/var/nix/profiles/system
      # Garbage collect unused packages
      - sudo nix-collect-garbage --delete-old
      # Optional: Clean home-manager generations
      - nix-collect-garbage --delete-old
    
  upgrade:
    desc: Update, Switch, and Clean
    output: 'prefixed'
    deps:
      - update
    cmds:
      - task: clean
      - task: deploy:all

  kwin_restart:
    desc: Restart KWin && Plasma
    cmds:
      - kwin_wayland --replace &
      - systemctl --user restart plasma-plasmashell

  new_install:
    desc: Fresh install on a new machine
    requires:
      vars:
        - name: TARGET_HOST_ROOT_ACCESSIBLE
    cmds:
      - "nix run github:nix-community/nixos-anywhere -- root@{{.TARGET_HOST_ROOT_ACCESSIBLE}} --flake .#curie --print-build-logs"
      - ssh user@{{.TARGET_HOST_ROOT_ACCESSIBLE}} "sudo nixos-generate-config --show-hardware-config" > hosts/curie/hardware-configuration.nix
      - ssh user@{{.TARGET_HOST_ROOT_ACCESSIBLE}} 'cat /etc/ssh/ssh_host_ed25519_key.pub'
      - echo "Add the above SSH host key as pubkey to the secrets.nix and rekey the secrets with `cd secrets && agenix -r`"
      - echo "afterwards just deploy to the new machine and the secrets should be in place"