# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Swapfile (8GB example)
  swapDevices = [{
    device = "/swapfile/swapfile";
    size = 8192;
    randomEncryption.enable = true;
  }];

  # Swapfile setup (now on ext4: disable CoW not needed, but truncate/mkswap)
  systemd.services.initrd-setup-swapfile = {
    wantedBy = [ "initrd-setup.service" ];
    before = [ "initrd-setup.service" ];
    script = ''
      truncate -s 8G /swapfile/swapfile
      chattr +C /swapfile/swapfile  # Optional: nodatacow-like
      mkswap /swapfile/swapfile
      chmod 600 /swapfile/swapfile
    '';
  };


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
